### PR TITLE
Update US Healthcare Map to use React

### PR DESCRIPTION
**Pull request by mmcfarland**
The existing application was was refactored into a React app, using the same
semantic structure, classes, and cartographic logic. Some updates and
refactoring were required to gain compatibility with the React rendering system.

This has feature parity and CI is building.

Further testing to make sure errors were not introduced is warranted.

cc: @jfrankl

### CODE REVIEW

**Comment by mmcfarland** [comment]
I should note that due to the missing features noted above, this isn't ready for deployment. I'm not sure if merging to master would actually release it publicly.

**Comment by mmcfarland** [comment]
Merged and rebuilding.

**Comment by mmcfarland** [comment]
Deploy preview is up and working, thanks @hectcastro 

https://5e878f90175e1d0006107c3c--covidcaremap.netlify.com/maps/us-healthcare-system-capacity-v2/

**Comment by jfrankl** [comment]
I noticed some spacing stuff. Here's how I'd fix it:

- For `.visualization` set `width: 380px`
- Use wrapper element around the map element and add `padding: 10px`

### Your PR
image

### Original
image

**Comment by mmcfarland** [comment]
@jfrankl @lossyrob 
I've finished the port to v2. There are some minor visual differences I couldn't track down:
* Some padding around elements in the header (links) and options bar (buttons). I think it has something to do with how the page css is normalized
* The mapbox zoom control is different and I can't figure out how to make it the nicer one from the original

Otherwise, the data and rendering appear to match between versions. Can you all check it out and provide feedback? I replaced the original with v2 in the last two commits, so the preview site should show the new one wherever the original one was.

**Comment by jfrankl** [comment]
@mmcfarland do you want me to make a commit with style fixes? That'd probably be easiest for me.

Should I update the copy to match the live version as well?

**Comment by mmcfarland** [comment]
@jfrankl Copy should be identical. Style fix commits welcome. Are you seen more differences than me?

covid-compare

**Comment by jfrankl** [comment]
Whoops, my bad. I do see all the changes now.

This line of css should fix zoom control:

```
.map button {
    border-radius: 0;
}
```

**Comment by mmcfarland** [comment]
Thanks. Just pushed a fix for the control

image

**Comment by hectcastro** [comment]
Looked for these changes on the base branch today and noticed the PR was still open. Does anything else have to be done before these changes can be merged?

**Comment by lossyrob** [comment]
No, I have been focused on the data release and have not gotten to review yet. Hoping to do so tonight; since Matt, Jeff and you have looked over I imagine it will be a quick look.

**Comment by jfrankl** [comment]
@lossyrob I'll take a look at the vector tiles disappearing part.

**Comment by mmcfarland** [comment]
After a conversation, the source maps are likely not loading because the environments being evaluated were using an optimized production bundle which has sourcemaps turned off. Running in the dev environment with `npm start` will likely load the maps.

**Comment by jfrankl** [comment]
@lossyrob I see what you are referring to on the staging site (https://deploy-preview-117--covidcaremap.netlify.com/maps/us-healthcare-system-capacity/#10.34/39.0379/-112.515/0.2).

However, I am not able to reproduce this locally. I'm stumped. I think it would make sense for someone else to work on this and see if they can recreate it locally, and then I'd be glad to play a support role to figure out the Mapbox settings that might fix it.

**Comment by mmcfarland** [comment]
@lossyrob @jfrankl Can you check the latest deploy preview and ensure that the issues are addressed (tiles, popup/mouse).

**Comment by jfrankl** [comment]
@mmcfarland yes on both counts. Excellent.

**Pull request merged**
