### PR TITLE
geocoding HCRIS

### LINKED ISSUE #34: Clean up erroneous geocoding of facilities
The geocoding done in https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/nbs/usa_hcris2018_facilitybedcounts_20200313_v1.ipynb is through gmaps/mapbox of the hospital facilities by name, street address, city, state, zipcode. The results are pretty good but there is a handful of what seem like obvious errors (facilities mapped to central America or Europe). 

While we've refactored the notebook in general (in #27), we skipped re-geocoding the facilities so those original errors remain in the produced data and would carry forward as we merge and aggregate more datasets.

We should correct the geolocation of these hospital facility points that are obviously wrong at least in the geojson file that would feed into downstream data processing notebooks (i.e. #32, #30 ). 

There doesn't seem to be that many like this so this could be manually corrected and saved as a new geojson file for the timebeing. Later, we could think about more automated ways to check and correct. In any case, such corrections should be documented in detail (which exact facilities were corrected, through what method) so we can maintain a good record of how the data is manipulated from raw sources to our produced finalized datasets.

### PR DESCRIPTION
**Pull request by simonkassel**
This PR adds a notebook that geocodes hospitals from hcris dataset. It also adds the output geojson and a simplified zip code geojson to the data directory.

close #34 

HCRIS facilities are geocoded using the [Google Maps](https://developers.google.com/maps/documentation/geocoding/start) and [Mapbox](https://docs.mapbox.com/api/search/) geocoding APIs. Google Maps is the primary source while Mapbox is used as a fallback option. We validate the geocoding results by checking their spatial overlap with administrative regions (states, counties, zip codes) that they are expected to fall into. We use three different level because of underlying inaccuracies in the HCRIS data.

Geocoding steps:
- Construct a query based on address info in the HCRIS record
- Find the geometries that the output point is expected to fall into based on the HCRIS record(state, county, zip code)
- Geocode using the Google Maps API
- If the point falls into the expected County or Zip Code, proceed, otherwise check it against its expected state geometry.
- Track the source of confirmation for each facility so that we can manually inspect the results that were confirmed at the higher geographic level (i.e. state)
TO DO

- [x] Finish geocoding all hospitals, working through all edge cases
- [x] Validate the results (visual sanity check + reasonable distance threshold between results of two geocoders)
- [x] Add extensive documentation
- [x] Forward api keys from env variables

### CODE REVIEW

**Comment by simonkassel** [comment]
@lossyrob I'm currently running this. Running into edge cases and fixing them on the fly. I'll let you know when it's done running and I have a full set of results to validate

**Comment by rcheetham** [comment]
When we've tested geocoders in the past, we've generally found Google's to be a higher quality result. It has much better building coverage and relies less on the road centerline. I think Mapbox has been getting better, so my suggestion would be to take Google first, then fall back to Mapbox on things that fail. Another API you might consider is ArcGIS Online - also fairly high quality. REST API is at https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm

**Comment by simonkassel** [comment]
thanks @rcheetham yeah, I am finding the same results. Google has been much more accurate so I switched to a process of only using mapbox when google fails

**Comment by lossyrob** [comment]
Thank you! This looks good, merging.

**Pull request merged**
